from selenium.webdriver.common.by import By
# Elementos:

from_field = (By.ID, 'from')
to_field = (By.ID, 'to')
map = (By.XPATH, '//*[@id="root"]/div/div[4]')
ask_taxi = (By.XPATH, "//button[@type='button' and @class='button round']")
select_comfort_tariff = (By.CSS_SELECTOR, "img[src='/static/media/kids.27f92282.svg']")
blanket = (By.CLASS_NAME, 'r-sw-label')
phone_number_field = (By.CLASS_NAME, 'np-text')
input_phone = (By.ID, 'phone')
next_button = (By.XPATH, "//button[@type='submit' and text()='Siguiente']")
code_element = (By.ID, 'code')
confirm_button = (By.XPATH, "//button[@type='submit' and text()='Confirmar']")
pay_button = (By.CLASS_NAME, 'pp-text')
add_card_button = (By.XPATH, "//img[@src='/static/media/plus.d25b8941.svg' and @class='pp-plus' and @alt='plus']")
cancel_button = (By.XPATH, "//button[@type='button' and text()='Cancelar']")
card_input = (By.CLASS_NAME, 'card-input')
code_input = (By.XPATH, "//input[@type='text' and @id='code' and @name='code' and @placeholder='12' and @class='card-input']")
card_number_label = (By.XPATH, "//div[@class='card-number-label' and text()='Número de tarjeta (no la tuya):']")
link_button = (By.XPATH, "//button[@class='button full' and text()='Enlace']")
checkmark = (By.CLASS_NAME, 'checkmark')
close_button = (By.XPATH, '//*[@id="root"]/div/div[2]/div[2]/div[1]/button')
comment = (By.ID, 'comment')
slider_round = (By.XPATH, '//*[@id="root"]/div/div[3]/div[3]/div[2]/div[2]/div[4]/div[2]/div[1]/div/div[2]/div/span')
counter_plus = (By.XPATH, '//*[@id="root"]/div/div[3]/div[3]/div[2]/div[2]/div[4]/div[2]/div[3]/div/div[2]/div[2]/div/div[2]/div/div[3]')
ask_taxi_button = (By.CLASS_NAME, 'smart-button-main')
timer = (By.XPATH, '//*[@id="root"]/div/div[5]/div[2]/div[1]/div/div[2]')
driver_icon = (By.XPATH, '//*[@id="root"]/div/div[5]/div[2]/div[2]/div[1]/div[1]/div[1]/img')
